@host = http://localhost:5214
@orderId = 00000000-0000-0000-0000-000000000001

POST {{host}}/orders
Content-Type: application/json
x-correlation-id: {{$guid}}

{
	"amount": 120.50,
	"customerEmail": "customer@example.com"
}

###

GET {{host}}/orders/{{orderId}}
Accept: application/json
x-correlation-id: {{$guid}}

###
